### PR TITLE
Fix incorrect city name

### PR DESCRIPTION
**Pull request by jawwad**
Update Pakistan, Pakistan -> Attock, Pakistan

### CODE REVIEW

**Comment by johnkennedy9147** [comment]
@jawwad Hi, the url https://www.facebook.com/groups/free.code.camp.attock is either incorrect or the facebook group has closed.  Can you advise?

**Comment by raisedadead** [comment]
Or it is not public?

**Comment by johnkennedy9147** [comment]
I should clarify my comment, the group might be "secret" both "open" and "closed" privacy groups can still be seen by non-members, for example the bronx group. What I meant was deleted but I had forgotten about the "secret" groups setting. So this fb group is either non longer existing, has an incorrect url entry on the directory, or has been set to privacy "secret". So we should either remove it from the directory, or correct the url.

**Comment by raisedadead** [comment]
Lets, remove this.

**Comment by johnkennedy9147** [comment]
@jawwad we are going to remove the entry for freeCodeCamp Attock unless we are provided with a correct URL for a group with privacy "open," additionally the co-ordinates appear to be incorrect, can you confirm the correct location if the entry needs retained, thanks

**Comment by jawwad** [comment]
@johnkennedy9147 - Sorry about the delayed response. I'm actually not sure if the group exists, I just saw that there was a mismatch between the url and the city name and so updated the city name. In this case I guess it can be removed.

**Comment by johnkennedy9147** [comment]
@jawwad could you please either amend this PR to remove the entry or close and I will do another to remove the entry, thanks
cc @raisedadead

**Pull request closed without merging**
