### PR TITLE
Added valley worx modesto freeCodeCamp to archive

### PR DESCRIPTION
**Pull request by mtpjr88**
Added valley worx modesto freeCodeCamp to archive.
So when new Free Code Campers are searching for groups in our area they find us!

### CODE REVIEW

**Comment by cameldjoulako** [comment]
M'y email is cameldjoulako1@gmail.com

Camel Léonce Djoulako
Le 8 janv. 2018 5:17 AM, "Michael Pimentel Jr" <notifications@github.com> a
écrit :

**Comment by cameldjoulako** [comment]
My email is cameldjoulako17@gmail.com

Camel Léonce Djoulako

**Comment by cameldjoulako** [comment]
Please add a student group **FreeCodeCamp Nongsamba** in to archive.
So when new Free Code Campers are searching for groups in our area they find us!
 Facebook link : https://web.facebook.com/groups/free.code.camp.nkongsamba/

**Comment by mtpjr88** [comment]
I believe you’ll have to submit the pull request and it has to be verified from a verified source contributor and or Quincy himself.

**Comment by cameldjoulako** [comment]
Please @mtpjr88 Help me i dons no to submit the pull request. 
I am a new here.
Thank you

**Comment by mtpjr88** [comment]
More than happy to. I can get to it later today.

**Comment by cameldjoulako** [comment]
thank @mtpjr88  I tell you about you

**Comment by mtpjr88** [comment]
@cameldjoulako could you tell me the city, state, and country, and perhaps a photo url ?

**Comment by johnkennedy9147** [comment]
@mtpjr88 @cameldjoulako Hi, I am working on adding a large number of missing groups to this directory so I will add this group also.

**Comment by mtpjr88** [comment]
Thanks! I need to make a change to my group as well. I will make the PR today.

**Comment by johnkennedy9147** [comment]
@mtpjr88 I just noticed you already submitted a PR for that group. So we can just let that get merged.

**Pull request merged**
