### PR TITLE
Add missing groups part 1

### PR DESCRIPTION
**Pull request by johnkennedy9147**
First tranche of missing groups to add to directory

### CODE REVIEW

**Comment by johnkennedy9147** [comment]
@QuincyLarson @raisedadead I split the additions into 5 sets, this is the first, let me know if you want smaller sets for the next ones

**Comment by johnkennedy9147** [comment]
Created an issue to track additions #68

**Comment by raisedadead** [comment]
Hi @johnkennedy9147 extremely sorry about the delays in getting back to you. Yes 5 sets per PR is a good size.

Thanks.

**Comment by johnkennedy9147** [comment]
@raisedadead No problem on the delay, I know there is a lot going on with beta and people have jobs, lives etc
I'll add the rest in smaller blocks so each PR is quicker to review.

**Comment by QuincyLarson** [comment]
@johnkennedy9147 Awesome! Thanks for your patience. I'm going to start reviewing and merging your other PRs as well :)

**Comment by johnkennedy9147** [comment]
@QuincyLarson  :+1:

**Pull request merged**
